In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [7]:
import requests
response = requests.get('https://randomuser.me/api', headers=headers)
response.status_code

200

In [8]:
response.json()

{'results': [{'gender': 'female',
   'name': {'title': 'Miss', 'first': 'Lourdes', 'last': 'Peña'},
   'location': {'street': {'number': 4976, 'name': 'Avenida de Andalucía'},
    'city': 'Burgos',
    'state': 'Andalucía',
    'country': 'Spain',
    'postcode': 51159,
    'coordinates': {'latitude': '-32.7735', 'longitude': '78.7739'},
    'timezone': {'offset': '+10:00',
     'description': 'Eastern Australia, Guam, Vladivostok'}},
   'email': 'lourdes.pena@example.com',
   'login': {'uuid': '8b2e7020-77de-4c9d-9638-91f9302f59fd',
    'username': 'orangemeercat178',
    'password': 'cheetah',
    'salt': 'C13VJ12A',
    'md5': '929a1d04ec8e243301c973c8879016b0',
    'sha1': '664a1d2a9f3538493374dc134a2488ab98ebc2c5',
    'sha256': 'cfda583c4d0297dcc5b19cb95ff4acb38c5aa3b9a5041977a04e5524f4e3f40c'},
   'dob': {'date': '2000-04-04T22:32:06.874Z', 'age': 23},
   'registered': {'date': '2013-11-04T03:50:07.040Z', 'age': 9},
   'phone': '901-935-986',
   'cell': '666-630-288',
   'id': {'name': 'DNI', 'value': '31433599-N'},
   'picture': {'large': 'https://randomuser.me/api/portraits/women/18.jpg',
    'medium': 'https://randomuser.me/api/portraits/med/women/18.jpg',
    'thumbnail': 'https://randomuser.me/api/portraits/thumb/women/18.jpg'},
   'nat': 'ES'}],
 'info': {'seed': '7ed6ab9c25c493c6',
  'results': 1,
  'page': 1,
  'version': '1.4'}}

In [11]:
df = pd.DataFrame(response.json()['results'])

In [12]:
df

,gender,name,location,email,login,dob,registered,phone,cell,id,picture,nat
0,female,"{'title': 'Miss', 'first': 'Lourdes', 'last': ...","{'street': {'number': 4976, 'name': 'Avenida d...",lourdes.pena@example.com,{'uuid': '8b2e7020-77de-4c9d-9638-91f9302f59fd...,"{'date': '2000-04-04T22:32:06.874Z', 'age': 23}","{'date': '2013-11-04T03:50:07.040Z', 'age': 9}",901-935-986,666-630-288,"{'name': 'DNI', 'value': '31433599-N'}",{'large': 'https://randomuser.me/api/portraits...,ES